### PR TITLE
GCS:SystemHealth: Add Uninitialised state for Gimbal alarm

### PR DESCRIPTION
**Pull request by tracernz**
Managed to fit it in before work. :)

### CODE REVIEW

**Comment by jihlein** [comment]
Something does not appear correct.  I can see there is a gimbal error present in the system:

image

But the alarm box never changes color, regardless of the alarm state:

image

How can I troubleshoot this?

**Comment by tracernz** [comment]
Ahhh :(. Will check after work. Can't really do anything until then sorry (probably a couple of hours since I am leaving early today).

**Comment by jihlein** [comment]
Not trying to rush, just trying to see what I can do to help/learn.  :)

**Comment by tracernz** [comment]
Here's the code that decides what to draw: https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/systemhealth/systemhealthgadgetwidget.cpp#L86

I wonder if you're getting these in the debug log gadget (System page I think) https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/systemhealth/systemhealthgadgetwidget.cpp#L123

**Comment by tracernz** [comment]
The elements in the SVG file containing the coloured boxes are called e.g. "Gimbal-Error", "Gimbal-Uninitialised"

**Comment by tracernz** [comment]
Perhaps I don't have an element called "Gimbal", required by this line https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/systemhealth/systemhealthgadgetwidget.cpp#L107, pretty sure that's what it is actually.

**Comment by jihlein** [comment]
There are some errors:

16:52:53[DEBUG][SystemHealth] Warning: The SystemHealth SVG does not contain a graphical element for the  "Geofence"  alarm.
16:52:53[DEBUG][SystemHealth] Warning: The SystemHealth SVG does not contain a graphical element for the  "GyroBias"  alarm.
16:52:53[DEBUG][SystemHealth] Warning: The SystemHealth SVG does not contain a graphical element for the  "Gimbal"  alarm.

**Comment by tracernz** [comment]
> 16:52:53[DEBUG][SystemHealth] Warning: The SystemHealth SVG does not contain a graphical element for the "Gimbal" alarm.

That confirms my theory. Just need to set the ID on the Gimbal text element to "Gimbal".

**Comment by jihlein** [comment]
Okay!  Gimbal module not enabled:

image

Gimbal module enabled, gimbal not powered:

image

Gimbal module enabled, gimbal powered:

image

I hand edited the SVG module, is that okay to commit or should it be updated via Inkscape?

**Comment by tracernz** [comment]
Looks good, that's fine. :D

**Comment by jihlein** [comment]
Very good, thanks for the help!

**Comment by tracernz** [comment]
No prob. If you want to learn more about GCS feel free to ask :D. I'm no expert but I've picked up a fair bit over the last few months.

**Pull request merged**
